
**Answer 1.1**

In [2]:
import pandas as pd
from datetime import datetime
import numpy as np

In [3]:
lt = pd.read_csv("HDFC.csv")#Reading the csv file of HDFC stock data

In [4]:
lt.describe()

,Prev Close,Open Price,High Price,Low Price,Last Price,Close Price,Average Price,Total Traded Quantity,Turnover,No. of Trades,Deliverable Qty,% Dly Qt to Traded Qty
count,829.000000,829.000000,829.000000,829.000000,829.000000,829.000000,829.000000,8.290000e+02,8.290000e+02,829.000000,8.290000e+02,829.000000
mean,1235.068637,1237.372376,1249.368938,1223.320869,1236.191858,1236.496562,1236.178492,1.763380e+06,3.107192e+09,67614.677925,1.241798e+06,72.594077
std,728.839077,730.235891,734.456171,724.421341,729.350445,729.566264,729.328719,1.650588e+06,3.092474e+09,63518.256040,1.183951e+06,15.632166
min,193.000000,193.000000,194.400000,190.250000,193.000000,193.000000,193.290000,7.300000e+03,1.445400e+06,1.000000,0.000000e+00,0.000000
25%,365.000000,367.450000,373.000000,357.000000,365.000000,365.000000,364.590000,1.460000e+05,5.301187e+07,18.000000,1.022000e+05,65.840000
50%,1700.800000,1705.000000,1715.000000,1685.050000,1701.000000,1702.100000,1703.630000,1.685595e+06,3.091969e+09,75553.000000,1.141221e+06,72.720000
75%,1858.900000,1864.000000,1881.500000,1847.050000,1860.050000,1859.550000,1865.270000,2.778618e+06,5.053920e+09,116325.000000,1.983472e+06,80.950000
max,2069.150000,2068.000000,2073.000000,2039.150000,2067.000000,2069.150000,2057.720000,9.486397e+06,1.749929e+10,312842.000000,6.951300e+06,100.000000

In [5]:
lt.tail()

,Symbol,Series,Date,Prev Close,Open Price,High Price,Low Price,Last Price,Close Price,Average Price,Total Traded Quantity,Turnover,No. of Trades,Deliverable Qty,% Dly Qt to Traded Qty
824,HDFC,EQ,07-May-2019,1965.45,1974.80,2009.15,1959.20,1964.50,1966.30,1983.01,2683956,5.322315e+09,114029,1522276,56.72
825,HDFC,EQ,08-May-2019,1966.30,1964.50,1964.50,1925.05,1930.10,1930.75,1941.55,3626183,7.040422e+09,151779,2378973,65.61
826,HDFC,EQ,09-May-2019,1930.75,1926.00,1931.60,1901.30,1914.15,1914.60,1918.15,1932792,3.707382e+09,130444,1132999,58.62
827,HDFC,EQ,10-May-2019,1914.60,1915.25,1956.00,1910.75,1926.80,1931.70,1936.05,1628923,3.153682e+09,97684,811832,49.84
828,HDFC,EQ,13-May-2019,1931.70,1926.10,1984.40,1917.85,1957.00,1952.90,1958.85,4509527,8.833504e+09,139299,1332224,29.54

In [6]:
lt = lt[lt["Series"]=="EQ"] # Dropping the rows which don't have Series = EQ

In [7]:
lt = lt.reset_index(drop=True)# Resetting the index of the dataframe

In [8]:
lt.tail()

,Symbol,Series,Date,Prev Close,Open Price,High Price,Low Price,Last Price,Close Price,Average Price,Total Traded Quantity,Turnover,No. of Trades,Deliverable Qty,% Dly Qt to Traded Qty
489,HDFC,EQ,07-May-2019,1965.45,1974.80,2009.15,1959.20,1964.50,1966.30,1983.01,2683956,5.322315e+09,114029,1522276,56.72
490,HDFC,EQ,08-May-2019,1966.30,1964.50,1964.50,1925.05,1930.10,1930.75,1941.55,3626183,7.040422e+09,151779,2378973,65.61
491,HDFC,EQ,09-May-2019,1930.75,1926.00,1931.60,1901.30,1914.15,1914.60,1918.15,1932792,3.707382e+09,130444,1132999,58.62
492,HDFC,EQ,10-May-2019,1914.60,1915.25,1956.00,1910.75,1926.80,1931.70,1936.05,1628923,3.153682e+09,97684,811832,49.84
493,HDFC,EQ,13-May-2019,1931.70,1926.10,1984.40,1917.85,1957.00,1952.90,1958.85,4509527,8.833504e+09,139299,1332224,29.54

In [9]:
lt.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 494 entries, 0 to 493
Data columns (total 15 columns):
Symbol                    494 non-null object
Series                    494 non-null object
Date                      494 non-null object
Prev Close                494 non-null float64
Open Price                494 non-null float64
High Price                494 non-null float64
Low Price                 494 non-null float64
Last Price                494 non-null float64
Close Price               494 non-null float64
Average Price             494 non-null float64
Total Traded Quantity     494 non-null int64
Turnover                  494 non-null float64
No. of Trades             494 non-null int64
Deliverable Qty           494 non-null int64
% Dly Qt to Traded Qty    494 non-null float64
dtypes: float64(9), int64(3), object(3)
memory usage: 58.0+ KB

**Answer 1.2**

In [10]:
lt["Close Price"].tail(90).max()#Maximun of last 90 values of close price

2069.15

In [11]:
lt["Close Price"].tail(90).min()# Minimun of last 90 values of close price

1841.0

In [12]:
lt["Close Price"].tail(90).mean()#Mean of last 90 values of close price

1955.255555555555

**Answer 1.3**

In [13]:
lt["Date"] = pd.to_datetime(lt["Date"]) # Converting the datatype of Date to datetime64

In [14]:
lt.head()

,Symbol,Series,Date,Prev Close,Open Price,High Price,Low Price,Last Price,Close Price,Average Price,Total Traded Quantity,Turnover,No. of Trades,Deliverable Qty,% Dly Qt to Traded Qty
0,HDFC,EQ,2017-05-15,1549.80,1554.5,1572.60,1554.10,1561.0,1559.50,1562.62,1270297,1.984990e+09,59917,955875,75.25
1,HDFC,EQ,2017-05-16,1559.50,1558.0,1569.00,1554.00,1568.0,1566.55,1564.05,2114918,3.307844e+09,79354,1652379,78.13
2,HDFC,EQ,2017-05-17,1566.55,1565.5,1570.95,1549.75,1550.1,1552.50,1557.08,2161434,3.365526e+09,80317,1794472,83.02
3,HDFC,EQ,2017-05-18,1552.50,1547.0,1558.60,1526.50,1545.0,1537.05,1539.03,2404372,3.700407e+09,85842,1837821,76.44
4,HDFC,EQ,2017-05-19,1537.05,1545.0,1548.00,1515.35,1526.5,1520.60,1526.14,2142433,3.269652e+09,113875,1601236,74.74

In [15]:
lt["Date"].max() - lt["Date"].min()

Timedelta('728 days 00:00:00')

**Answer 1.4**

In [16]:
lt["Month"] = lt.Date.dt.month #Making new column month

In [17]:
lt["Year"] = lt.Date.dt.year # Making new column year

In [18]:
vwap = []
for names, groups in lt.groupby(["Year","Month"]):
        vwap.append(((groups["Close Price"]*groups["Total Traded Quantity"]).mean())/groups["Total Traded Quantity"].mean())
        
# Here the vwap list stores all the vwap values for all the groups

In [19]:
vwap

[1551.858138913995,
 1634.1428740467704,
 1682.241746273039,
 1743.6680497928237,
 1765.3935468022196,
 1730.3141761266031,
 1706.2832725810447,
 1693.3585958249928,
 1854.5974754796118,
 1827.5515163669852,
 1810.5208333772725,
 1844.8727109539368,
 1864.6813814172367,
 1865.7245560566346,
 1969.0964244381214,
 1940.0868376189403,
 1829.37307556748,
 1718.956780934347,
 1862.6938009734954,
 1946.048384117358,
 1962.2585270951733,
 1901.9682539374974,
 1939.8934103810745,
 2004.1132218400637,
 1958.0939693452451]

**Answer 1.5**

In [20]:
def avg_price(N):
    return(lt["Close Price"].tail(N).mean())

In [21]:
avg_price(7)

1952.5857142857144

In [22]:
avg_price(14)

1963.0071428571428

In [23]:

avg_price(90)

1955.255555555555

In [24]:

avg_price(180)

1904.292500000002

In [25]:

avg_price(365)

1870.3546575342468

In [26]:
def profit_loss(N):
    prof_loss = lt["Close Price"].tail(N)
    a=prof_loss.values[0]
    b=prof_loss.values[N-1]
    c = ((b-a)/b)*100
    print((c))

In [27]:
profit_loss(7)

-2.739515592196221

In [28]:
profit_loss(14)

-0.051205898919555536

In [29]:
profit_loss(90)

-0.7911311383071237

In [30]:
profit_loss(180)

0.5837472476829377

In [31]:
profit_loss(365)

12.668339392698044

**Answer 1.6**

In [32]:
lt["Day_Perc_Change"]= lt["Close Price"].pct_change()*100#Adding a new column Day_Perc_Change

The first element is nan because there is no previous element to calculate the percentage.

In [33]:
lt["Day_Perc_Change"][0] = 0

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

**Answer 1.7**

In [40]:
def trend(lt):
    prc = (np.nditer(lt["Day_Perc_Change"]))
    for i in prc:
        if i>=-0.5 and i<=0.5:
            return "Slight or No change"
        if i>0.5 and i<=1:
            return "Slight Positive"
        if i>=1 and i<3:
            return "Positive"
        if i>=3 and i<7:
            return "Among Top Gainers"
        if i<-0.5 and i>=-1:
            return "Slight Negative"
        if i<=-3 and i>-7:
            return "Among top losers"
        if i<-1 and i>-3:
            return "Negative"
        if i>=7:
            return "Bull run"
        if i<=-7:
            return "Bear drop"

In [41]:
lt["Trend"] = lt.apply(trend,axis=1)

In [42]:
lt["Trend"].value_counts()

Slight or No change    152
Positive                98
Negative                96
Slight Positive         70
Slight Negative         63
Among Top Gainers        9
Among top losers         6
Name: Trend, dtype: int64

**Answer 1.8**

In [43]:
med  = lt.groupby(["Trend"])
med["Total Traded Quantity"].median()

Trend
Among Top Gainers      6450539.0
Among top losers       4736399.5
Negative               2807872.5
Positive               2915465.5
Slight Negative        2224803.0
Slight Positive        2434008.5
Slight or No change    2247984.0
Name: Total Traded Quantity, dtype: float64

In [44]:
med["Total Traded Quantity"].mean()

Trend
Among Top Gainers      6.352677e+06
Among top losers       5.186927e+06
Negative               3.028490e+06
Positive               3.075714e+06
Slight Negative        2.494395e+06
Slight Positive        2.583997e+06
Slight or No change    2.506236e+06
Name: Total Traded Quantity, dtype: float64

In [45]:
lt.to_csv("week2.csv",index="False")

In [46]:
pwd

'E:\\Python'

In [47]:
lt

,Symbol,Series,Date,Prev Close,Open Price,High Price,Low Price,Last Price,Close Price,Average Price,Total Traded Quantity,Turnover,No. of Trades,Deliverable Qty,% Dly Qt to Traded Qty,Month,Year,Day_Perc_Change,Trend
0,HDFC,EQ,2017-05-15,1549.80,1554.50,1572.60,1554.10,1561.00,1559.50,1562.62,1270297,1.984990e+09,59917,955875,75.25,5,2017,0.000000,Slight or No change
1,HDFC,EQ,2017-05-16,1559.50,1558.00,1569.00,1554.00,1568.00,1566.55,1564.05,2114918,3.307844e+09,79354,1652379,78.13,5,2017,0.452068,Slight or No change
2,HDFC,EQ,2017-05-17,1566.55,1565.50,1570.95,1549.75,1550.10,1552.50,1557.08,2161434,3.365526e+09,80317,1794472,83.02,5,2017,-0.896875,Slight Negative
3,HDFC,EQ,2017-05-18,1552.50,1547.00,1558.60,1526.50,1545.00,1537.05,1539.03,2404372,3.700407e+09,85842,1837821,76.44,5,2017,-0.995169,Slight Negative
4,HDFC,EQ,2017-05-19,1537.05,1545.00,1548.00,1515.35,1526.50,1520.60,1526.14,2142433,3.269652e+09,113875,1601236,74.74,5,2017,-1.070232,Negative
5,HDFC,EQ,2017-05-22,1520.60,1530.00,1530.00,1510.25,1519.95,1519.85,1518.84,1920867,2.917481e+09,70390,1541085,80.23,5,2017,-0.049323,Slight or No change
6,HDFC,EQ,2017-05-23,1519.85,1521.70,1537.20,1503.45,1510.00,1511.50,1521.20,1408855,2.143149e+09,56848,969791,68.84,5,2017,-0.549396,Slight Negative
7,HDFC,EQ,2017-05-24,1511.50,1519.00,1541.75,1512.40,1525.00,1524.85,1527.90,2209471,3.375851e+09,75808,1361319,61.61,5,2017,0.883229,Slight Positive
8,HDFC,EQ,2017-05-25,1524.85,1533.90,1546.00,1530.50,1539.00,1539.75,1539.88,4099792,6.313184e+09,91104,3327557,81.16,5,2017,0.977145,Slight Positive
9,HDFC,EQ,2017-05-26,1539.75,1538.10,1563.00,1530.25,1544.50,1547.90,1548.63,1871008,2.897491e+09,59347,1270174,67.89,5,2017,0.529307,Slight Positive
10,HDFC,EQ,2017-05-29,1547.90,1546.00,1601.25,1546.00,1596.75,1598.85,1586.02,3464406,5.494627e+09,75137,1961992,56.63,5,2017,3.291556,Among Top Gainers
11,HDFC,EQ,2017-05-30,1598.85,1595.70,1604.00,1575.05,1582.60,1579.50,1588.05,1605211,2.549149e+09,77293,1019565,63.52,5,2017,-1.210245,Negative
12,HDFC,EQ,2017-05-31,1579.50,1581.00,1596.15,1565.40,1576.80,1569.85,1571.89,4907685,7.714320e+09,160031,3833239,78.11,5,2017,-0.610953,Slight Negative
13,HDFC,EQ,2017-06-01,1569.85,1551.80,1587.40,1551.80,1577.25,1583.75,1575.11,2990228,4.709942e+09,155736,1983472,66.33,6,2017,0.885435,Slight Positive
14,HDFC,EQ,2017-06-02,1583.75,1582.00,1612.80,1582.00,1595.35,1604.65,1602.17,3427957,5.492167e+09,99348,2572628,75.05,6,2017,1.319653,Positive
15,HDFC,EQ,2017-06-05,1604.65,1606.40,1612.00,1591.15,1605.00,1606.15,1603.91,2988075,4.792594e+09,81217,2167100,72.52,6,2017,0.093478,Slight or No change
16,HDFC,EQ,2017-06-06,1606.15,1610.00,1624.85,1602.50,1603.70,1605.75,1611.85,2170920,3.499205e+09,48603,1537563,70.83,6,2017,-0.024904,Slight or No change
17,HDFC,EQ,2017-06-07,1605.75,1609.70,1611.50,1590.60,1600.00,1599.35,1598.75,1726464,2.760191e+09,69120,1256284,72.77,6,2017,-0.398568,Slight or No change
18,HDFC,EQ,2017-06-08,1599.35,1608.90,1635.00,1605.00,1631.00,1633.55,1628.23,2289492,3.727828e+09,104016,1459772,63.76,6,2017,2.138369,Positive
19,HDFC,EQ,2017-06-09,1633.55,1628.00,1649.00,1620.10,1646.10,1647.20,1636.33,2633241,4.308860e+09,73460,1898414,72.09,6,2017,0.835603,Slight Positive
20,HDFC,EQ,2017-06-12,1647.20,1644.00,1651.80,1633.85,1647.00,1647.50,1643.89,2000556,3.288695e+09,71819,1467513,73.36,6,2017,0.018213,Slight or No change
21,HDFC,EQ,2017-06-13,1647.50,1642.05,1682.20,1642.05,1665.00,1667.65,1667.32,2737084,4.563601e+09,143134,1840910,67.26,6,2017,1.223065,Positive
22,HDFC,EQ,2017-06-14,1667.65,1661.55,1668.00,1644.00,1647.10,1651.10,1651.72,6519614,1.076859e+10,139220,6014688,92.26,6,2017,-0.992414,Slight Negative
23,HDFC,EQ,2017-06-15,1651.10,1648.70,1653.70,1629.55,1635.00,1636.85,1642.13,5678766,9.325296e+09,73070,5097448,89.76,6,2017,-0.863061,Slight Negative
24,HDFC,EQ,2017-06-16,1636.85,1634.30,1651.00,1629.15,1635.20,1640.85,1641.87,2692532,4.420795e+09,73989,1737533,64.53,6,2017,0.244372,Slight or No change
25,HDFC,EQ,2017-06-19,1640.85,1659.00,1660.00,1645.20,1659.60,1654.20,1652.88,2907637,4.805977e+09,62546,2321542,79.84,6,2017,0.813603,Slight Positive
26,HDFC,EQ,2017-06-20,1654.20,1651.15,1660.00,1627.90,1632.15,1631.50,1636.96,2304515,3.772390e+09,67469,1652828,71.72,6,2017,-1.372265,Negative
27,HDFC,EQ,2017-06-21,1631.50,1632.15,1638.00,1615.50,1626.00,1628.25,1622.59,2359678,3.828801e+09,85584,1833784,77.71,6,2017,-0.199203,Slight or No change
28,HDFC,EQ,2017-06-22,1628.25,1626.10,1660.00,1626.10,1650.10,1653.80,1651.94,3438975,5.680997e+09,129910,2724127,79.21,6,2017,1.569169,Positive
29,HDFC,EQ,2017-06-23,1653.80,1660.00,1661.00,1642.10,1650.20,1651.35,1651.51,2590704,4.278584e+09,119288,1946085,75.12,6,2017,-0.148144,Slight or No change
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
464,HDFC,EQ,2019-03-27,1946.30,1955.55,1959.00,1906.00,1914.10,1919.90,1937.71,3076446,5.961253e+09,161822,2146231,69.76,3,2019,-1.356420,Negative
465,HDFC,EQ,2019-03-28,1919.90,1917.00,1950.00,1912.05,1942.10,1944.45,1942.93,6370987,1.237836e+10,151893,5177109,81.26,3,2019,1.278712,Positive
466,HDFC,EQ,2019-03-29,1944.45,1950.05,1972.25,1936.05,1964.00,1968.25,1956.38,4320179,8.451925e+09,148642,3200934,74.09,3,2019,1.223997,Positive
467,HDFC,EQ,2019-04-01,1968.25,1968.10,1975.00,1945.05,1951.00,1959.65,1960.06,3328552,6.524154e+09,168073,2370360,71.21,4,2019,-0.436936,Slight or No change
468,HDFC,EQ,2019-04-02,1959.65,1966.10,2001.00,1955.00,1998.95,1995.95,1979.73,3655232,7.236387e+09,159005,2561511,70.08,4,2019,1.852372,Positive
469,HDFC,EQ,2019-04-03,1995.95,2004.00,2032.45,1997.15,2008.75,2013.10,2019.73,4345772,8.777270e+09,109651,2926819,67.35,4,2019,0.859240,Slight Positive
470,HDFC,EQ,2019-04-04,2013.10,2008.00,2058.80,2006.30,2041.90,2042.05,2037.46,4463212,9.093604e+09,154293,3106308,69.60,4,2019,1.438081,Positive
471,HDFC,EQ,2019-04-05,2042.05,2045.00,2065.00,2035.00,2064.50,2059.20,2055.28,2576789,5.296023e+09,125822,1692384,65.68,4,2019,0.839842,Slight Positive
472,HDFC,EQ,2019-04-08,2059.20,2068.00,2072.50,2029.25,2052.00,2054.90,2048.64,2057768,4.215626e+09,114354,1387042,67.41,4,2019,-0.208819,Slight or No change
473,HDFC,EQ,2019-04-09,2054.90,2062.50,2073.00,2039.15,2067.00,2069.15,2057.72,2381281,4.900013e+09,162102,1662887,69.83,4,2019,0.693464,Slight Positive
474,HDFC,EQ,2019-04-10,2069.15,2067.50,2068.00,2025.10,2029.95,2029.25,2038.39,3036356,6.189267e+09,151203,2155517,70.99,4,2019,-1.928328,Negative
475,HDFC,EQ,2019-04-11,2029.25,2028.00,2048.00,2017.50,2018.10,2022.80,2029.46,2521729,5.117742e+09,160208,1690856,67.05,4,2019,-0.317851,Slight or No change
476,HDFC,EQ,2019-04-12,2022.80,2024.00,2029.90,2008.10,2023.00,2024.95,2020.07,2121821,4.286233e+09,102234,1519702,71.62,4,2019,0.106288,Slight or No change
477,HDFC,EQ,2019-04-15,2024.95,2034.90,2034.90,2010.00,2012.00,2014.25,2019.10,1333222,2.691910e+09,76176,811985,60.90,4,2019,-0.528408,Slight Negative
478,HDFC,EQ,2019-04-16,2014.25,2019.70,2034.30,2016.10,2027.20,2026.70,2025.80,2000314,4.052236e+09,166866,1489678,74.47,4,2019,0.618096,Slight Positive
479,HDFC,EQ,2019-04-18,2026.70,2040.00,2047.90,1998.15,2005.00,2003.75,2013.04,3888701,7.828095e+09,175404,2147684,55.23,4,2019,-1.132383,Negative
480,HDFC,EQ,2019-04-22,2003.75,2005.00,2010.00,1948.00,1958.50,1953.90,1970.41,2002662,3.946056e+09,80677,1361456,67.98,4,2019,-2.487835,Negative
481,HDFC,EQ,2019-04-23,1953.90,1958.00,1966.25,1929.60,1930.00,1934.70,1944.34,2848980,5.539373e+09,109800,1999347,70.18,4,2019,-0.982650,Slight Negative
482,HDFC,EQ,2019-04-24,1934.70,1943.90,1985.00,1933.25,1984.70,1980.40,1958.44,2758373,5.402103e+09,115391,1799052,65.22,4,2019,2.362123,Positive
483,HDFC,EQ,2019-04-25,1980.40,1987.55,1998.80,1946.55,1951.45,1955.15,1970.35,4162465,8.201508e+09,136733,2807343,67.44,4,2019,-1.274995,Negative
484,HDFC,EQ,2019-04-26,1955.15,1959.30,1982.15,1941.60,1976.95,1977.40,1963.96,2094836,4.114177e+09,102041,1440081,68.74,4,2019,1.138020,Positive
485,HDFC,EQ,2019-04-30,1977.40,1977.40,1999.85,1954.20,1995.55,1995.05,1976.43,3675345,7.264045e+09,122095,2606623,70.92,4,2019,0.892586,Slight Positive
486,HDFC,EQ,2019-05-02,1995.05,1995.00,2027.90,1989.25,2018.00,2017.40,2012.44,2380823,4.791258e+09,124835,1428794,60.01,5,2019,1.120273,Positive
487,HDFC,EQ,2019-05-03,2017.40,2017.50,2037.60,2000.00,2002.80,2006.40,2020.47,1451357,2.932422e+09,80223,850504,58.60,5,2019,-0.545256,Slight Negative
488,HDFC,EQ,2019-05-06,2006.40,1987.25,1993.95,1957.00,1965.90,1965.45,1967.93,2216418,4.361748e+09,89509,1394023,62.90,5,2019,-2.040969,Negative
489,HDFC,EQ,2019-05-07,1965.45,1974.80,2009.15,1959.20,1964.50,1966.30,1983.01,2683956,5.322315e+09,114029,1522276,56.72,5,2019,0.043247,Slight or No change
490,HDFC,EQ,2019-05-08,1966.30,1964.50,1964.50,1925.05,1930.10,1930.75,1941.55,3626183,7.040422e+09,151779,2378973,65.61,5,2019,-1.807964,Negative
491,HDFC,EQ,2019-05-09,1930.75,1926.00,1931.60,1901.30,1914.15,1914.60,1918.15,1932792,3.707382e+09,130444,1132999,58.62,5,2019,-0.836463,Slight Negative
492,HDFC,EQ,2019-05-10,1914.60,1915.25,1956.00,1910.75,1926.80,1931.70,1936.05,1628923,3.153682e+09,97684,811832,49.84,5,2019,0.893137,Slight Positive
493,HDFC,EQ,2019-05-13,1931.70,1926.10,1984.40,1917.85,1957.00,1952.90,1958.85,4509527,8.833504e+09,139299,1332224,29.54,5,2019,1.097479,Positive